/**
 * Generate the Markdown docs (<output>/policies/<branch>/README.md) of a
 * branch of a product from its policy schema. The overview of all templates
 * is generated by update_all_policy_templates.js.
 */

import { runTool } from "./modules/branches.mjs";
import { generateDocs } from "./modules/generate_markdown.mjs";

await runTool({
    usage: `
Usage:

    node generate_docs.js [options]

Options:`,
    outputs: [
        (branchData, values, { app, branches }, output) => generateDocs(branchData, { app, branches, output }),
    ],
});
