/**
 * Generate the Markdown docs (<output>/policies/<branch>/README.md) of the
 * branches of a product from their policy schema. The overview of all
 * templates is generated by generate_overview.js.
 */

import { runTool } from "./modules/branches.mjs";
import { generateDocs } from "./modules/generate_markdown.mjs";

await runTool({
    usage: `
Usage:

    node generate_docs.js [options]

Options:`,
    outputs: [
        (branchData, values, { app, branches }, output) => generateDocs(branchData, { app, branches, output }),
    ],
});
